import PDFDocument from "pdfkit";
import { IAccountingToolResult } from "../models/AccountingToolResult";

/**
 * Generate PDF from accounting tool result
 */
export const generatePDF = async (
  result: IAccountingToolResult
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Header
      doc
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("Smart AGI Accountant Platform", { align: "center" })
        .moveDown(0.5);

      doc
        .fontSize(16)
        .font("Helvetica-Bold")
        .text(result.title, { align: "center" })
        .moveDown(0.5);

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Generated: ${new Date().toLocaleString()}`, { align: "center" })
        .moveDown(1);

      // Tool Type
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text(`Tool: ${formatToolType(result.toolType)}`)
        .moveDown(1);

      // Results based on tool type
      switch (result.toolType) {
        case "balance_sheet":
          renderBalanceSheet(doc, result);
          break;
        case "profit_loss":
          renderProfitLoss(doc, result);
          break;
        case "depreciation":
          renderDepreciation(doc, result);
          break;
        case "break_even":
          renderBreakEven(doc, result);
          break;
        default:
          doc.text("Result data not available");
      }

      // Footer
      doc
        .moveDown(2)
        .fontSize(8)
        .text("This document was generated by Smart AGI Accountant Platform", {
          align: "center",
        });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

function formatToolType(type: string): string {
  return type
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(value);
}

function renderBalanceSheet(
  doc: PDFKit.PDFDocument,
  result: IAccountingToolResult
) {
  const { results } = result;

  doc.fontSize(12).font("Helvetica-Bold").text("Assets").moveDown(0.5);
  doc.fontSize(10).font("Helvetica");
  doc.text(`Current Assets: ${formatCurrency(results.totalCurrentAssets)}`);
  doc.text(`Fixed Assets: ${formatCurrency(results.totalFixedAssets)}`);
  doc
    .font("Helvetica-Bold")
    .text(`Total Assets: ${formatCurrency(results.totalAssets)}`)
    .moveDown(1);

  doc.font("Helvetica-Bold").text("Liabilities").moveDown(0.5);
  doc.fontSize(10).font("Helvetica");
  doc.text(
    `Current Liabilities: ${formatCurrency(results.totalCurrentLiabilities)}`
  );
  doc.text(
    `Long-term Liabilities: ${formatCurrency(results.totalLongTermLiabilities)}`
  );
  doc
    .font("Helvetica-Bold")
    .text(`Total Liabilities: ${formatCurrency(results.totalLiabilities)}`)
    .moveDown(1);

  doc.font("Helvetica-Bold").text("Equity").moveDown(0.5);
  doc
    .fontSize(10)
    .font("Helvetica-Bold")
    .text(`Total Equity: ${formatCurrency(results.totalEquity)}`)
    .moveDown(1);

  doc
    .fontSize(12)
    .font("Helvetica-Bold")
    .text(
      `Total Liabilities & Equity: ${formatCurrency(
        results.totalLiabilitiesAndEquity
      )}`
    )
    .moveDown(0.5);

  doc.text(`Status: ${results.isBalanced ? "✓ Balanced" : "✗ Not Balanced"}`);
}

function renderProfitLoss(
  doc: PDFKit.PDFDocument,
  result: IAccountingToolResult
) {
  const { results } = result;

  doc.fontSize(10).font("Helvetica");
  doc.text(`Total Revenue: ${formatCurrency(results.totalRevenue)}`);
  doc.text(`Cost of Goods Sold: ${formatCurrency(results.costOfGoodsSold)}`);
  doc
    .font("Helvetica-Bold")
    .text(`Gross Profit: ${formatCurrency(results.grossProfit)}`)
    .font("Helvetica")
    .text(`Gross Profit Margin: ${results.grossProfitMargin.toFixed(2)}%`)
    .moveDown(0.5);

  doc.text(
    `Operating Expenses: ${formatCurrency(results.totalOperatingExpenses)}`
  );
  doc
    .font("Helvetica-Bold")
    .text(`Operating Income: ${formatCurrency(results.operatingIncome)}`)
    .font("Helvetica")
    .text(`Operating Margin: ${results.operatingMargin.toFixed(2)}%`)
    .moveDown(0.5);

  doc.text(`Income Before Tax: ${formatCurrency(results.incomeBeforeTax)}`);
  doc.text(`Tax Expense: ${formatCurrency(results.taxExpense)}`);
  doc
    .fontSize(12)
    .font("Helvetica-Bold")
    .text(`Net Income: ${formatCurrency(results.netIncome)}`)
    .fontSize(10)
    .font("Helvetica")
    .text(`Net Profit Margin: ${results.netProfitMargin.toFixed(2)}%`);
}

function renderDepreciation(
  doc: PDFKit.PDFDocument,
  result: IAccountingToolResult
) {
  const { inputs, results } = result;

  doc.fontSize(10).font("Helvetica");
  doc.text(`Asset: ${inputs.assetName}`);
  doc.text(`Cost: ${formatCurrency(inputs.cost)}`);
  doc.text(`Salvage Value: ${formatCurrency(inputs.salvageValue)}`);
  doc.text(`Useful Life: ${inputs.usefulLife} years`);
  doc.text(`Method: ${formatToolType(results.method)}`);
  doc.moveDown(1);

  doc.font("Helvetica-Bold").text("Depreciation Schedule").moveDown(0.5);

  // Table header
  doc.font("Helvetica-Bold").fontSize(9);
  const tableTop = doc.y;
  const col1 = 50;
  const col2 = 150;
  const col3 = 280;
  const col4 = 410;

  doc.text("Year", col1, tableTop);
  doc.text("Depreciation", col2, tableTop);
  doc.text("Accumulated", col3, tableTop);
  doc.text("Book Value", col4, tableTop);

  doc.moveDown(0.3);
  doc.font("Helvetica").fontSize(9);

  results.schedule.forEach((item: any) => {
    const y = doc.y;
    doc.text(item.year.toString(), col1, y);
    doc.text(formatCurrency(item.depreciation), col2, y);
    doc.text(formatCurrency(item.accumulated), col3, y);
    doc.text(formatCurrency(item.bookValue), col4, y);
    doc.moveDown(0.3);
  });

  doc
    .moveDown(0.5)
    .fontSize(10)
    .font("Helvetica-Bold")
    .text(`Total Depreciation: ${formatCurrency(results.totalDepreciation)}`);
}

function renderBreakEven(
  doc: PDFKit.PDFDocument,
  result: IAccountingToolResult
) {
  const { inputs, results } = result;

  doc.fontSize(10).font("Helvetica");
  doc.text(`Fixed Costs: ${formatCurrency(inputs.fixedCosts)}`);
  doc.text(
    `Variable Cost per Unit: ${formatCurrency(inputs.variableCostPerUnit)}`
  );
  doc.text(`Price per Unit: ${formatCurrency(inputs.pricePerUnit)}`);
  doc.moveDown(1);

  doc.font("Helvetica-Bold").text("Results").moveDown(0.5);
  doc.font("Helvetica");
  doc.text(
    `Contribution Margin per Unit: ${formatCurrency(
      results.contributionMarginPerUnit
    )}`
  );
  doc.text(
    `Contribution Margin Ratio: ${results.contributionMarginRatio.toFixed(2)}%`
  );
  doc.moveDown(0.5);

  doc
    .fontSize(12)
    .font("Helvetica-Bold")
    .text(`Break-Even Point: ${results.breakEvenUnits} units`)
    .text(`Break-Even Revenue: ${formatCurrency(results.breakEvenRevenue)}`);
}

export default generatePDF;
